/**
 * Typed access to the Census numbers in census.json.
 *
 * census.json is generated by `npm run data:census`; this file only reshapes it.
 * If you want to change *which* years the page compares, change it here.
 */
import raw from "./census.json";

export type AcsMeasure = keyof Omit<(typeof raw.acs1)[number], "year">;

export interface Observation {
  year: number;
  value: number;
  /** 90% margin of error, when the source publishes one. */
  moe?: number;
}

export const ARVADA_GEOID = raw.geography.geoid;

/** Year of the last comprehensive plan; the "before" in every before/after. */
export const PLAN_YEAR = 2014;

// ---------------------------------------------------------------------------
// Population estimates
// ---------------------------------------------------------------------------

export const populationSeries: Observation[] = raw.population.series.map((d) => ({
  year: d.year,
  value: d.population,
}));

export const populationVintage = raw.population.vintage;

function populationIn(year: number): Observation {
  const found = populationSeries.find((d) => d.year === year);
  if (!found) throw new Error(`No population estimate for ${year}`);
  return found;
}

export const population = {
  planYear: populationIn(PLAN_YEAR),
  peak: populationSeries.reduce((a, b) => (b.value > a.value ? b : a)),
  latest: populationSeries[populationSeries.length - 1],
};

// ---------------------------------------------------------------------------
// American Community Survey (1-year estimates)
// ---------------------------------------------------------------------------

/** One year-by-year series for an ACS measure, e.g. acsSeries("medianGrossRent"). */
export function acsSeries(measure: AcsMeasure): Observation[] {
  return raw.acs1.map((row) => ({
    year: row.year,
    value: row[measure].estimate,
    moe: row[measure].moe,
  }));
}

/** First and latest ACS observation for a measure. */
export function acsBeforeAfter(measure: AcsMeasure) {
  const series = acsSeries(measure);
  const before = series.find((d) => d.year === PLAN_YEAR);
  if (!before) throw new Error(`No ACS ${measure} for ${PLAN_YEAR}`);
  return { before, after: series[series.length - 1] };
}

export const ACS_LATEST_YEAR = raw.acs1[raw.acs1.length - 1].year;

/**
 * Link to a table on data.census.gov, filtered to Arvada.
 * These are the human-friendly versions of what the fetch script downloads.
 */
export function acsTableUrl(table: string, year: number): string {
  return `https://data.census.gov/table/ACSDT1Y${year}.${table}?g=160XX00US${ARVADA_GEOID}`;
}
